### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by catgirlcataclysm** [GreenChild04/safe-vex-template#1]
When running ``cargo build`` from a fresh clone, it fails almost instantly with this error:

```
Updating crates.io index
  Downloaded cpufeatures v0.2.12
  Downloaded 1 crate (12.8 KB) in 1.06s
error: package `home v0.5.9` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.67.0-nightly
Either upgrade to rustc 1.70.0 or newer, or use
cargo update -p home@0.5.9 --precise ver
where `ver` is the latest version of `home` supporting rustc 1.67.0-nightly
```

Changing the release channel to ``stable`` in ``rust-toolchain`` fixes this, but then another error shows up:
```
error[E0463]: can't find crate for `core`
  |
  = note: the `armv7a-vex-eabi` target may not be installed
  = help: consider downloading the target with `rustup target add armv7a-vex-eabi`

error[E0463]: can't find crate for `compiler_builtins`
```

**Comment by GreenChild04** [comment]
Sorry for being a bit late but, if you follow the instructions of the compiler by running `rustup target add armv7z-vex-eabi`, it should solve the issue, also, make sure you have the `arm-none-eabi` toolchain installed as well. In future, I'll probably add a dockerfile to the project to make the build fully reproducible. If you have any further problems building the project please let me know :D!

**Comment by kalscium** [comment]
Sorry for the late response, but, you can fix this issue by re-cloning the `safe-vex-template` repo or pulling the latest commit as I've fixed the problem by updating the toolchain versions.

Also, make sure you have the `arm-none-eabi` toolchain, `gcc` and `libclang-dev` installed as well (as the `error[E0463]: can't find crate for 'compiler_builtins'` is caused by not having `gcc` installed). In future, I'll probably add a dockerfile to the project to make the build fully reproducible. If you have any further problems with compiling this project please let me know :D!

**Comment by kalscium** [comment]
**(Update)** I've added a dockerfile, updated the [`README.md`](https://github.com/GreenChild04/safe-vex-template/blob/main/README.md) to remove any ambiguity and also updated the `rust-toolchain` file in `safe-vex-template`
